apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: titanic-api-secret
  namespace: prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: titanic-api-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "/titanic-api/prod/rds"
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "/titanic-api/prod/rds"
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: "/titanic-api/prod/rds"
        property: POSTGRES_DB
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: "/titanic-api/prod/rds"
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: "/titanic-api/prod/rds"
        property: POSTGRES_PORT
