apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: titanic-api-db-credentials
  namespace: prod
spec:
  refreshInterval: 5m          # how often to check for changes
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: titanic-api-secret   # ← this is the Secret name your Deployment expects
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        POSTGRES_PORT: "{{ .POSTGRES_PORT }}"
        SQLALCHEMY_DATABASE_URI: "{{ .SQLALCHEMY_DATABASE_URI }}"
  dataFrom:
    - extract:
        key: /titanic-api/prod/rds   # ← exact name from your Terraform secret
