apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: titanic-api-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: titanic-api-secret
    creationPolicy: Merge
  data:
    - secretKey: SQLALCHEMY_DATABASE_URI   # The key in the K8s secret
      remoteRef:
        key: /titanic-api/prod/rds        # The ARN/name of the secret in Secrets Manager
        property: SQLALCHEMY_DATABASE_URI
